# Generated by Django 3.0.3 on 2020-02-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=30)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('R', 'Ready'), ('W', 'Working'), ('B', 'Broke'), ('I', 'Inactive')], default='R', max_length=1)),
                ('cron', models.CharField(max_length=50)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('schema', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
